name: Push to External Docs Repo

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    name: Push to AviatrixSystems Docs
    if: (${{github.repository}} == "AviatrixDev/Documentation")
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@d4fffb50872869abe2d9a9098a6d9c5aa7d16be4
        with:
          key: ${{ secrets.DOCS_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DOCS_KNOWN_HOSTS }}
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Git push
        run: |
          git remote add prod-doc git@github.com:AviatrixSystems/Docs.git
          git push --force prod-doc main-copy
        env:
          KEY_FILE : ${{secrets.DOCS_PRIVATE_KEY}}



